name: droidsec.org
markdown: redcarpet
pygments: true
redcarpet:
  extensions: ["no_intra_emphasis"]
title: droidsec.org News
production_url: http://www.droidsec.org
atom_path: atom.xml
rss_path: rss.xml
join_email: "join (dot) droidsec (at) qoop (dot) org"


#
# If you want to become a member, contact the address in "join_email" above or visit /join/
#
members:
  jduck:
    name: Joshua J. Drake
    display_name: jduck
    gravatar: 0fa6f5c062dc47e825d9bf7a2b40711d
    email: jduck[dot]droidsec[at]qoop[dot]org
    web: http://qoop.org/
    twitter: jduck
    github: jduck
    title: Group Founder
    bio: Joshua J. Drake is a Director of Research Science at Accuvant LABS and lead author of the Android Hacker's Handbook. Joshua focuses on original research such as reverse engineering and the analysis, discovery, and exploitation of security vulnerabilities. He has over 10 years of experience auditing and exploiting a wide range of application and operating system software with a focus on Android since early 2012. In prior roles, he served at Metasploit and VeriSign’s iDefense Labs. Joshua previously spoke at BlackHat, RSA, CanSecWest, REcon, Ruxcon/Breakpoint, Toorcon, and DerbyCon. Other notable accomplishments include exploiting Oracle's JVM for a win at Pwn2Own 2013, successfully compromising the Android browser via NFC with Georg Wicherski at BlackHat USA 2012, and winning the DefCon 18 CTF with the ACME Pharm team in 2010.

  quine:
    name: Zach Lanier
    display_name: quine
    gravatar:
    email: zach[at]n0where[dot]org
    web: https://n0where.org/
    twitter: quine
    github: quine
    title: Security Researcher
    bio: Zach Lanier is a Senior Security Researcher at Duo Security and a co-author of the "Android Hacker's Handbook". Zach has been researching mobile and embedded device security since 2009, ranging from app security, to platform security (especially Android); to device, network, and carrier security. He has presented at various public and private industry conferences, such as BlackHat, DEFCON, INFILTRATE, EUSecWest, ShmooCon, RSA, Amazon ZonCon, and more. Most recently, he worked as a Senior Research Scientist at Accuvant LABS.

  pof:
    name: Pau Oliva Fora
    display_name: pof
    gravatar: c9a1e06b9dc0abecada691129ebc3a6d
    email: pau[at]eslack[dot]org
    web: http://pof.eslack.org
    twitter: pof
    github: poliva
    title: Unicorn Consultant
    bio: Pau Oliva (@pof) is a Mobile Security Engineer with viaForensics. He has 10 years of experience working as R+D Engineer in a Wireless Service Provider. His passion for smartphones started back in 2004 when he had his first PocketPC phone with the Windows Mobile operating system and started reverse engineering and hacking HTC devices. He has been actively researching security aspects on the Android operating system since its debut with the T-Mobile G1 on October 2008. Pau has spoken at a variety of security conferences, including DefCon and RSA in USA and LaCon and NoConName in Spain, and is co-author of the upcoming Wiley's Android Hacker's Handbook.

  Gunther:
    name: Jacob Soo
    display_name: Gunther
    gravatar: 
    email: deviant[dot]beta[at]gmail[dot]com
    web: http://xchg.info/
    twitter: Gunther_AR
    github: jacobsoo
    title: Couch Potato
    bio: 

  jcase:
    name: Jon Sawuer
    display_name: jcase
    gravatar:
    email: jcase[at]cunninglogic[dot]com
    web: http://cunninglogic.com/
    twitter: TeamAndirc
    github: CunningLogic
    title: Security Researcher
    bio: Very opinionated mobile security researcher.

  0xroot: 
    name: Sebastián Guerrero 
    display_name: 0xroot 
    gravatar: 
    email: s[dot]guerrero0[at]gmail[dot]com 
    web: http://seguesec.com/
    twitter: 0xroot 
    github: 0xroot 
    title: Security Researcher 
    bio: I like to break things.
    
  saidelike:
    name: Cedric Halbronn
    display_name: saidelike
    gravatar: 
    email: saidelike+droidsec[at]gmail[dot]com
    web: http://saidsecurity.wordpress.com/
    twitter: saidelike
    github: saidelike
    title: Security Researcher
    bio: Passionate

  thomc:
    name: Thomas Cannon
    display_name: thomc
    gravatar: c6a2d0bf364b80a01ab150a3e3c7e571
    email: mail[at]thomascannon[dot]net
    web: http://thomascannon.net/
    twitter: thomas_cannon
    github: thomascannon
    title: Security Researcher
    bio: Thomas is Dir. of R&D at viaForensics and spends his time developing mobile security research into products, services, OSS and training. Thomas has performed mobile security assessments for clients in banking, network, government, medical and OEM markets. He has presented at international conferences including DEF CON and has a solid track record in corporate security and startup environments.

  diff:
    name: Tim Strazzere
    display_name: diff
    gravatar: 6a4b43066d19111e850cb14b45eacf93
    email: diff[at]lookout[dot].com
    web: http://www.strazzere.com/blog
    twitter: timstrazz
    github: strazzere
    title: Security Researcher
    bio: Tim Strazzere is a Lead Research and Response Engineer at Lookout Mobile Security. Along with writing security software, he specializes in reverse engineering and malware analysis. Some interesting past projects include having reversing the Android Market protocol, Dalvik decompilers and memory manipulation on mobile devices. Past speaking engagements have included DEFCON, BlackHat, SyScan, HiTCON and EICAR.
    
  anwarelmakrahy:
    name: Anwar Mohamed
    display_name: anwarelmakrahy
    gravatar: b6660f74a947f3ad51963a33c8635146
    email: anwarelmakrahy[at]gmail[dot]com
    web: http://anwarelmakrahy.blogspot.com/
    twitter: anwarelmakrahy
    github: AnwarMohamed
    title: Vuln Miner
    bio: 21-year-old security researcher, gained his experience over nine years working on security-related tools and frameworks. In this time he has become skilled with a number of languages including C/C++, Java, Python & Assembly. His qualifications includes reverse engineering and detailed knowledge of security tools, technologies and best practices.

  nanotechz9l:
    name: Rick Flores
    display_name: nanotechz9l
    gravatar: bec95b5640474b27e965961c7b55eb1c
    email: 0xnanoquetz9l[at]gmail[dot].com
    web:
    twitter: nanotechz9l
    github: nanotechz9l
    title: Free Diver
    bio: Rick is a Software security test engineer, and penetration tester at a software company. His focuses in both hardware/software security to include vuln research, exploit dev, malware analysis, and detection/intell automation. He's a student of ruby, c, and x86/x64/arm asm. He's also an avid follower of metasploit-framework, nanoelectronics, and embedded systems. Rick has presented his exploit dev workshop at ToorCON 13 in San Diego, and BSidesLV 2012 in Las Vegas.
    
  vesh:
    name: Angelo Vescio IV
    display_name: vesh
    gravatar: 80f5f9816070e1bbc3eb95e137c7e8d1
    email: vesh[at]satxhackers[dot]org
    web: http://satxhackers.org/
    twitter: angelovescio
    github: darkparticlelabs
    title: Chimney Sweep
    bio: Angelo Vescio spends most of his time trying to figure out how to get obscure devices in places they aren't supposed to be...also wolfman

  imcom:
    name: Yu Jin
    display_name: imcom
    gravatar: 37941e596475a3c78282921d031ead38
    email: jinyu.bjut[at]gmail[dot]com
    web:
    twitter: imcomjin
    github: imcom
    title: Developer
    bio: Yu Jin is a web developer at a network security company. He is interested in network security and Android security. Specifically he is keen on cryptography, protocols and Android security.

  anantshri:
    name: Anant Shrivastava
    display_name: AnantShri
    gravatar: 44e20881e1877a59f626bd2311ad2141
    email: anant[at]anantshri[dot]info
    web: http://anantshri.info/
    twitter: anantshri
    github: anantshri
    title: Security Researcher
    bio: Anant Shrivastava is a Security Researcher and Consultant. He is the creator of Android Tamer (a VM for Android security professionals) and an active blogger. He spoke or trained others at various conferences like Nullcon, c0c0n, Clubhack, and g0s. His talks were focused on various aspects of the Android operating system since 2011. His expertise remains in Linux, web applications (dev and security testing) and mobile devices (OS and application) security.

  marcograss:
    name: Marco Grassi
    display_name: marcograss
    gravatar: a98925181b2256d38addf9c3f5bf4dea
    email: marco.gra[at]gmail[dot]com
    web:
    twitter: marcograss
    github: marco-gra
    title: Security Researcher
    bio: R&D Team Member at viaForensics. I like to reverse stuff, find vulns, write tools. If some hardware is involved, even more.

  corrupt:
    name: Prashant Mahajan
    display_name: corrupt
    gravatar:
    email: prashant3535[at]gmail[dot]com
    web: http://prashantmahajan.wordpress.com/
    twitter: prashant3535
    github: prashant3535
    title: Security Consultant
    bio: Prashant Mahajan is a Security Researcher and Consultant. He is interested in mobile device (OS and application) security.

  cocaman:
    name: Corsin Camichel
    display_name: cocaman
    gravatar: a0c74ac4c9cee42281206e16fe472136
    email: cocaman[at]gmaildot[]com
    web: http://camichel.com/
    twitter: cocaman
    github: cocaman
    title: Security Analyst
    bio: Team-Lead Android Security and Assessments for Compass Security. Also breaking other stuff in job and free time. And I code.

  k3170makan:
    name: k3170makan 
    display_name: k3170makan 
    gravatar: 6c9e182b4cb6abb2889d8dc56aa04d5c
    email: k3170makan[at]gmail[dot]com
    web: http://blog.k3170makan.com/
    twitter: k3170makan 
    github: k3170makan 
    title: Security Analyst
    bio: "I Fight for the users"

  dweinstein:
    name: David Weinstein
    display_name: insitusec
    gravatar: 6c9e182b4cb6abb2889d8dc56aa04d5c
    email: dweinst@insitusec.com
    twitter: insitusec
    github: dweinstein
    title: Security Engi-nerd
    bio: "Senior Security Engineer @ viaForensics."
