name: droidsec.org
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "with_toc_data"]

#
# atom / rss info
#
title: droidsec.org News
production_url: http://www.droidsec.org
atom_path: atom.xml
rss_path: rss.xml
join_email: "join (dot) droidsec (at) qoop (dot) org"


#
# If you want to become a member, contact the address in "join_email" above or visit /join/
#
members:
  jduck:
    name: Joshua J. Drake
    display_name: jduck
    gravatar: 0fa6f5c062dc47e825d9bf7a2b40711d
    email: jduck[dot]droidsec[at]qoop[dot]org
    web: http://qoop.org/
    twitter: jduck
    github: jduck
    title: Group Founder
    bio: Joshua J. Drake is the Sr. Director of Platform Research and Exploitation at Zimperium and Lead Author of the Android Hacker's Handbook. Joshua focuses on original research such as reverse engineering and the analysis, discovery, and exploitation of security vulnerabilities. He has over 10 years of experience in the field and regularly speaks at top industry conferences. Joshua was previously a Director of Research Science at Accuvant, where he headed up a team of elite vulnerability researchers. Prior to Accuvant, Joshua also worked with Rapid7’s Metasploit and VeriSign’s iDefense Labs. Additional notable accomplishments include exploiting Oracle’s JVM for a win at Pwn2Own 2013, successfully compromising the Android browser via NFC with Georg Wicherski at BlackHat USA 2012, and winning the DefCon 18 CTF with the ACME Pharm team in 2010.

  quine:
    name: Zach Lanier
    display_name: quine
    gravatar:
    email: zach[at]n0where[dot]org
    web: https://n0where.org/
    twitter: quine
    github: quine
    title: Security Researcher
    bio: Zach Lanier is a Senior Security Researcher at Duo Security and a co-author of the "Android Hacker's Handbook". Zach has been researching mobile and embedded device security since 2009, ranging from app security, to platform security (especially Android); to device, network, and carrier security. He has presented at various public and private industry conferences, such as BlackHat, DEFCON, INFILTRATE, EUSecWest, ShmooCon, RSA, Amazon ZonCon, and more. Most recently, he worked as a Senior Research Scientist at Accuvant LABS.

  pof:
    name: Pau Oliva Fora
    display_name: pof
    gravatar: c9a1e06b9dc0abecada691129ebc3a6d
    email: pau[at]eslack[dot]org
    web: http://pof.eslack.org
    twitter: pof
    github: poliva
    title: Unicorn Consultant
    bio: Pau Oliva is a Mobile Security Engineer with NowSecure. He has 10 years of experience working as R+D Engineer in a Wireless Service Provider. His passion for smartphones started back in 2004 when he had his first PocketPC phone with the Windows Mobile operating system and started reverse engineering and hacking HTC devices. He has been actively researching security aspects on the Android operating system since its debut with the T-Mobile G1 on October 2008. Pau has spoken at a variety of security conferences, including DefCon and RSA in USA and LaCon and NoConName in Spain, and is co-author of the upcoming Wiley's Android Hacker's Handbook.

  jacbosoo:
    name: Jacob Soo
    display_name: jacbosoo
    gravatar:
    email: jacob[dot]soo[at]gmail[dot]com
    web: http://vxsecurity.sg/ & http://xchg.info/
    twitter: _jsoo_
    github: jacobsoo
    title: Couch Potato
    bio:

  jcase:
    name: Jon Sawuer
    display_name: jcase
    gravatar:
    email: jcase[at]cunninglogic[dot]com
    web: http://cunninglogic.com/
    twitter: jcase
    github: CunningLogic
    title: Security Researcher
    bio: Very opinionated mobile security researcher.

  0xroot:
    name: Sebastián Guerrero
    display_name: 0xroot
    gravatar:
    email: s[dot]guerrero0[at]gmail[dot]com
    web: http://seguesec.com/
    twitter: 0xroot
    github: 0xroot
    title: Security Researcher
    bio: I like to break things.

  saidelike:
    name: Cedric Halbronn
    display_name: saidelike
    gravatar:
    email: saidelike+droidsec[at]gmail[dot]com
    web: http://saidsecurity.wordpress.com/
    twitter: saidelike
    github: saidelike
    title: Security Researcher
    bio: Passionate

  thomc:
    name: Thomas Cannon
    display_name: thomc
    gravatar: c6a2d0bf364b80a01ab150a3e3c7e571
    email: mail[at]thomascannon[dot]net
    web: http://thomascannon.net/
    twitter: thomas_cannon
    github: thomascannon
    title: Security Researcher
    bio: Thomas is a penetration tester and security researcher with a focus on improving the security of mobile.

  diff:
    name: Tim Strazzere
    display_name: diff
    gravatar: 6a4b43066d19111e850cb14b45eacf93
    email: diff[at]lookout[dot].com
    web: http://www.strazzere.com/blog
    twitter: timstrazz
    github: strazzere
    title: Security Researcher
    bio: Tim Strazzere is a Lead Research and Response Engineer at Lookout Mobile Security. Along with writing security software, he specializes in reverse engineering and malware analysis. Some interesting past projects include having reversing the Android Market protocol, Dalvik decompilers and memory manipulation on mobile devices. Past speaking engagements have included DEFCON, BlackHat, SyScan, HiTCON and EICAR.

  anwarelmakrahy:
    name: Anwar Mohamed
    display_name: anwarelmakrahy
    gravatar: b6660f74a947f3ad51963a33c8635146
    email: anwarelmakrahy[at]gmail[dot]com
    web: http://anwarelmakrahy.blogspot.com/
    twitter: anwarelmakrahy
    github: AnwarMohamed
    title: Vuln Miner
    bio: 21-year-old security researcher, gained his experience over nine years working on security-related tools and frameworks. In this time he has become skilled with a number of languages including C/C++, Java, Python & Assembly. His qualifications includes reverse engineering and detailed knowledge of security tools, technologies and best practices.

  nanotechz9l:
    name: Rick Flores
    display_name: nanotechz9l
    gravatar: bec95b5640474b27e965961c7b55eb1c
    email: 0xnanoquetz9l[at]gmail[dot].com
    web:
    twitter: nanotechz9l
    github: nanotechz9l
    title: Free Diver
    bio: Rick is a Software security test engineer, and penetration tester at a software company. His focuses in both hardware/software security to include vuln research, exploit dev, malware analysis, and detection/intell automation. He's a student of ruby, c, and x86/x64/arm asm. He's also an avid follower of metasploit-framework, nanoelectronics, and embedded systems. Rick has presented his exploit dev workshop at ToorCON 13 in San Diego, and BSidesLV 2012 in Las Vegas.

  vesh:
    name: Angelo Vescio IV
    display_name: vesh
    gravatar: 80f5f9816070e1bbc3eb95e137c7e8d1
    email: vesh[at]satxhackers[dot]org
    web: http://satxhackers.org/
    twitter: angelovescio
    github: darkparticlelabs
    title: Chimney Sweep
    bio: Angelo Vescio spends most of his time trying to figure out how to get obscure devices in places they aren't supposed to be...also wolfman

  imcom:
    name: Yu Jin
    display_name: imcom
    gravatar: 37941e596475a3c78282921d031ead38
    email: jinyu.bjut[at]gmail[dot]com
    web:
    twitter: imcomjin
    github: imcom
    title: Developer
    bio: Yu Jin is a web developer at a network security company. He is interested in network security and Android security. Specifically he is keen on cryptography, protocols and Android security.

  marcograss:
    name: Marco Grassi
    display_name: marcograss
    gravatar: a98925181b2256d38addf9c3f5bf4dea
    email: marco.gra[at]gmail[dot]com
    web:
    twitter: marcograss
    github: marco-gra
    title: Security Researcher
    bio: R&D Team Member at NowSecure. I like to reverse stuff, find vulns, write tools. If some hardware is involved, even more.

  corrupt:
    name: Prashant Mahajan
    display_name: corrupt
    gravatar:
    email: prashant3535[at]gmail[dot]com
    web: http://prashantmahajan.wordpress.com/
    twitter: prashant3535
    github: prashant3535
    title: Security Consultant
    bio: Prashant Mahajan is a Security Researcher and Consultant. He is interested in mobile device (OS and application) security.

  cocaman:
    name: Corsin Camichel
    display_name: cocaman
    gravatar: a0c74ac4c9cee42281206e16fe472136
    email: cocaman[at]gmaildot[]com
    web: http://camichel.com/
    twitter: cocaman
    github: cocaman
    title: Security Officier
    bio: Working for a Bank in IT Security. Also breaking other stuff in job and free time. And I code.

  k3170makan:
    name: k3170makan
    display_name: k3170makan
    gravatar: 6c9e182b4cb6abb2889d8dc56aa04d5c
    email: k3170makan[at]gmail[dot]com
    web: http://blog.k3170makan.com/
    twitter: k3170makan
    github: k3170makan
    title: Security Analyst
    bio: "I Fight for the users"

  dweinstein:
    name: David Weinstein
    display_name: insitusec
    gravatar:
    email: dweinst[at]insitusec[dot]com
    twitter: insitusec
    github: dweinstein
    title: Senior Security Engineer @ NowSecure
    bio: Security Engi-nerd

  adroidman:
    name: Grady Duncan
    display_name: aDroidman
    gravatar:
    email:
    twitter: adroidman
    github: adroidman
    title: Software Engineer
    bio: Software Developer, SharePoint/Salesforce Admin. Spend my free time dabbling in web development.

  sunnyrockzzs:
    name: Subho Halder
    display_name: Subho Halder
    gravatar: 835f347c1e05f21094de2f24e0f69daf
    email: security[at]xysec[dot]com
    twitter: sunnyrockzzs
    github: subho007
    title: Co-Founder and Security Researcher @ XYSec Labs
    bio: Programmer, Entrepreneur, Freelancer, Pentester and Exploiter. Loves to exploit Android. Lead Programmer and Creator of AFE.

  utkanos:
    name: Drew Suarez
    display_name: utkanos
    gravatar: e9610997926c08a1f9ba5a7a4e0a86c7
    email: utkanos[at]gmail[dot]org
    twitter: utkan0s
    github: utkanos
    title: Security Consultant/Researcher
    bio: Breaking things at Matasano, contributor to cyanogenmod, photographer, and craft beer snob.

  rexperience7:
    name: Rex Kim
    display_name: Rex
    gravatar: 3637f3816716c93afb13426107ffb110
    email: rexperience7[at]gmail[dot]com
    twitter:  rexperience7
    github: rex2er
    title: Security Researcher, Vuln Miner
    bio: 20 year old hacker. Peace, love, beer, zeroday!

  warlord:
    name: John Troony
    display_name: warlord
    gravatar: bf4094519cd2c9c94e8ce4f5a5d9efe9
    email: jayombagi[at]gmail[dot]com
    twitter:  johntroony
    github: johntroony
    title: (in)security
    bio: Animal lover.. hacking for fun & profit.

  mspreitz:
    name: Michael Spreitzenbarth
    display_name: mspreitz
    gravatar: 19984ec57f0c768074d4759bcb4c3788
    email: research[at]spreitzenbarth[dot]de
    web: http://forensics.spreitzenbarth.de
    twitter: m_spreitz
    github: mspreitz
    title: Security Researcher
    bio: Mobile security consultant and free time researcher in the field of Android malware analysis and forensics. Lead developer of the MobileSandbox system. Additionaly, giving talks and trainings in the afore mentioned topics.

  cryptax:
    name: Axelle Apvrille
    display_name: cryptax
    twitter: cryptax
    github: cryptax
    title: Security Researcher
    bio: Fighting malware that get on strange stuff. Talked at VB, ShmooCon, BlackHat Europe, Insomni'Hack, Hack.lu...

  fuzion24:
    name: Ryan Welton
    display_name: fuzion24
    twitter: fuzion24
    github: fuzion24
    title: Security Researcher @ NowSecure
    bio: I like to break things. I enjoy offensive security especially for Android/Linux.

  scottyab:
    name: Scott Alexander-Bown
    display_name: scottyab
    gravatar: e86e5dcb2b81622818b4b24ca3c1beec
    twitter: scottyab
    github: scottyab
    web: http://alexander-bown.com
    title: Developer/consultant
    bio: App Developer, trainer, speaker and co-author of the Android Security Cookbook.

  adi0x90:
    name: Aditya Gupta
    display_name: adi0x90
    gravatar: dc6c5033a5f09182c497c05372bfe35f
    email: adi[at]attify[dot]com
    twitter: adi1391
    github: adi0x90
    website: http://blog.attify.com
    title: Android Hacker @ Attify
    bio: Co-Founder and Droid Ninja at Attify. Author of "Learning Pentesting for Android Devices" . Speaker & Trainer at BlackHat, OWASP AppSec, Toorcon, Syscan, Nullcon etc. Co-Creator of AppWatch - The Mobile Security Platform. Found vulnerabilities in Google, Facebook, Twitter, Paypal, Skype, Webkit, Apple etc. in the past.

  Zenofex:
    name: Amir Etemadieh
    display_name: Zenofex
    gravatar: b2068df9f0e5062aa740acd02d81db40
    email: Zenofex[at]Exploitee[dot]rs
    twitter: zenofex
    github: zenofex
    web: http://exploitee.rs
    title: Research Scientist
    bio: Research Scientist @ Accuvant Labs. Founder of Exploitee.rs . Speaker 3 x @ DEFCON, 1 x @ Infosec Southwest, and 2 x @ BSides Austin

  uberlaggydarwin:
    name: Brin Taylor
    display_name: uberlaggydarwin
    gravatar: e3929a249aa245d63ecdccf2cd975419
    email: security[at]brinly[dot]me
    twitter: uberlaggydarwin
    github: uberlaggydarwin
    web: http://brinly.me
    title: Security Researcher
    bio:  Independent security researcher from Australia.. Likes reversing bootloaders. Does CyanogenMod dev in spare time.

  revskills:
    name: Francisco Alonso
    display_name: revskills
    gravatar: 071bd2e4be2d1ff668db28d9c5852557
    email: rs[at]revskills[dot]cz
    twitter: revskills
    github: revskills
    web: http://revskills.cz
    title: Security Engineer
    bio: Security Engineer at Red Hat (Czech Republic) & Fedora Security Team. Hardware Hacking, Biker, PGP 0xE2E64DCA

  oguzhantopgul:
    name: Oguzhan Topgul
    display_name: oguzhantopgul
    gravatar: 5ea6c463b17758d63ffdab4587c15a00
    email: oguzhantopgul[at]gmail[dot]com
    twitter: oguzhantopgul
    github: oguzhantopgul
    web: http://oguzhantopgul.com
    title: Security Researcher
    bio: Mobile Security Researcher

  dmc:
    name: Dominic Chell
    display_name: dmc
    gravatar: 13c0a52d5dad4051f19f92acc96632d8
    email: dominic[at]mdsec[dot]co[dot]uk
    twitter: domchell
    github: dmchell
    web: http://www.mobileapphacker.com
    title: Security Researcher
    bio: Does computering for @MDSecLabs, lead author for the Mobile App Hacker's Handbook

  virqdroid:
    name: Nikolaos Chrysaidos
    display_name: virqdroid
    gravatar: ef3c0249ddfae3b9912dc96dba43c3c8
    email:
    twitter: virqdroid
    github: virqdroid
    web: http://www.virqdroid.com
    title: Security Researcher
    bio: Nikolaos Chrysaidos is Mobile Malware & Security Analyst at Avast Virus Lab. Personal motto is "Whatever goes around, unlocks around"

  linkdead13:
    name: Colby marquis
    display_name: linkdead13
    twitter: Venomouslord
    github: camarquis
    title: Security Researcher / Student
    bio: Horrible @ Self Writing

  haykuro:
    name: Steve Birstok
    display_name: haykuro
    gravatar: ccf3b16f23720b67467df21093751adf
    email: haykuro[at]gmail[dot]com
    web: http://stevebirstok.com/
    twitter: haykuro
    github: haykuro
    title: Security Researcher, Software Engineer
    bio: Good at computers. "He can unjam the printer really fast."
